# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

- name: .NET
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  AZURE_WEBAPP_NAME: CalculusApi
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ./CaculusApi.sln --configuration Release  --no-restore
    - name: Publish
      run: dotnet publish ./CaculusApi.sln --configuration Release  --no-build --output '${{env.AZURE_WEBAPP_PACKAGE_PATH}}'
    - name: Deployment
      uses: actions/webapps-deploy@v2
      with:
       app-name: ${{env.AZURE_WEBAPP_NAME}}
       publish-profile: ${{secrets.AZURE_PUBLISH_PROFILE}}
       package: "${{env.AZURE_WEBAPP_PACKAGE_PATH}}"
